### ISSUE TITLE
Incompatability with Rails 5.2 (testing)

### ISSUE THREAD

**Issue by Schwad** [biola/Voight-Kampff#30] opened 2017-11-09 10:17 UTC
I know Rails 5.2 isn't live yet, but I'm testing the alpha against tools I like to see what is and isn't working so we're ready for the bump. 

Everything bundle installs correctly, however calling `request.bot?` in the controller returns:

`NoMethodError: undefined method `bot?' for #<ActionDispatch::Request:0x00007f9f27b45550>`

**Comment by mikebaldry** [comment] 2018-09-10 13:05
This happens to me also, on 4.2.10 in testing only.

**Comment by adamcrown** [comment] 2018-09-30 04:12
Hmm, it does look like `ActionDispatch::Request` no longer inherits from `Rack::Request`. I'll be honest, I probably don't have time to fix this now, but I'm happy to accept PRs or I can try to get to it as soon as I have some spare time.

**Comment by fschwahn** [comment] 2019-10-31 10:30
I cannot reproduce this:

- Since 113c2994a524c2372b84986ee5715e638049ae45 the methods are added directly to `ActionDispatch::Request`.
- I can call `request.bot?` in a rails 5.2 app without problem from a controller.

**Comment by adamcrown** [comment] 2023-03-12 18:18
Sorry for the long period of silence. But I'm trying to come back to this gem and get it in shape. I just merged https://github.com/biola/Voight-Kampff/pull/50 and am about to push up V2.

This should bring the Rails support up to current levels. If it does not, please submit a new issue for new issues with Rails 7+. Thanks.

**Closed by adamcrown** 2023-03-12 18:18 UTC
Labels: bug
