### ISSUE TITLE
import_user_agents rake task

### ISSUE THREAD

**Issue by filipeperdigaosousa** [biola/Voight-Kampff#37] opened 2018-07-26 23:13 UTC
I'm trying to run this task in order to update the user agents list but it seems not working properly.

`Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8
/usr/local/bundle/gems/voight_kampff-1.1.1/lib/tasks/voight_kampff.rake:12:in `write'
/usr/local/bundle/gems/voight_kampff-1.1.1/lib/tasks/voight_kampff.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => voight_kampff:import_user_agents`

**Comment by adamcrown** [comment] 2018-09-30 04:13
I believe this is a duplicate of https://github.com/biola/Voight-Kampff/issues/33 which should be fixed by https://github.com/biola/Voight-Kampff/pull/34 and in the next release.

**Closed by adamcrown** 2018-09-30 04:14 UTC
Labels: bug
